### ISSUE TITLE
Nice work, no issue at all for this time

### ISSUE THREAD

**Issue by blaisexen** [CarlosHe/OpenCV-Android-Firemonkey#1]
do you have screenshots of the running program under android device?

**Comment by CarlosHe** [comment]
Yes, I have!

I will upload the screenshots later, and videos too!

**Comment by CarlosHe** [comment]
![](https://raw.githubusercontent.com/CarlosHe/OpenCV-Android-Firemonkey/master/doc/screenshots/screenshot_001.webp)

![](https://raw.githubusercontent.com/CarlosHe/OpenCV-Android-Firemonkey/master/doc/screenshots/screenshot_002.webp)

**Comment by blaisexen** [comment]
Hi, is that real?
can you put that on the project sample you have?
and let us test the way it work?

lots of the Delphi guys gets exited :)

**Comment by CarlosHe** [comment]
See in the samples folder, I uploaded an contour example...

**Comment by blaisexen** [comment]
Solved :1st_place_medal:
